(() => {
const cfg=window.FELJ_CLOUD_CONFIG||{}, supabase=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
let user=null,page='dashboard',cache={};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v?new Intl.DateTimeFormat('pt-BR').format(new Date(v)): '—';
const status=v=>{let c=['concluida','aprovado','disponivel'].includes(String(v).toLowerCase())?'green':['atrasada','reprovado','bloqueada'].includes(String(v).toLowerCase())?'red':['risco','parada','pendente'].includes(String(v).toLowerCase())?'yellow':'blue';return '<span class="status '+c+'">'+esc(v||'—')+'</span>'};
async function q(table,select='*',limit=100){const r=await supabase.from(table).select(select).limit(limit);if(r.error)throw r.error;return r.data||[]}
async function init(){const s=await supabase.auth.getSession();await setSession(s.data.session);supabase.auth.onAuthStateChange((_e,s)=>setSession(s));}
async function setSession(s){user=s?.user||null;$('#connection').textContent=user?((user.email||'Usuário')+' · online'):'Não autenticado';if(!user){$('#authDialog').showModal();return}renderPage()}
async function renderPage(){const titles={dashboard:'Visão executiva',clientes:'Comercial',engenharia:'Engenharia',os:'Ordens de Serviço',pcp:'PCP / APS',producao:'Chão de Fábrica',estoque:'Materiais / Estoque',qualidade:'Qualidade',custos:'Custos',expedicao:'Faturamento / Expedição',correcoes:'Correções'};$('#pageTitle').textContent=titles[page]||'FELJ Industrial';$('#newAction').style.display=['dashboard','pcp','producao','correcoes'].includes(page)?'none':'inline-block';try{$('#content').innerHTML=await pages[page]()}catch(e){$('#content').innerHTML='<div class="panel error">Erro: '+esc(e.message)+'</div>'}}
const pages={
dashboard:async()=>{const [os,comp,op,maq,nc,estoque]=await Promise.all([q('ordens_servico','id,numero,status,prioridade,prazo,valor,custo_real,clientes(razao_social),extrusoras(nome)',200),q('componentes_os','id,status',500),q('operacoes_producao','id,status',500),q('maquinas','id,nome,setor,status',100),q('nao_conformidades','id,status',300),q('itens_estoque','id,saldo,reservado',300)]);const atrasadas=os.filter(x=>x.prazo&&new Date(x.prazo)<new Date()&&!['concluida','cancelada'].includes(x.status)).length;const risco=op.filter(x=>['parada','atrasada'].includes(x.status)).length;return '<div class="cards"><div class="card"><small>OS abertas</small><strong>'+os.filter(x=>x.status!=='concluida'&&x.status!=='cancelada').length+'</strong></div><div class="card"><small>Em produção</small><strong>'+op.filter(x=>x.status==='em_execucao'||x.status==='produzindo').length+'</strong></div><div class="card"><small>OS em atraso</small><strong>'+atrasadas+'</strong></div><div class="card"><small>Riscos produção</small><strong>'+risco+'</strong></div><div class="card"><small>Não conformidades</small><strong>'+nc.filter(x=>x.status!=='encerrada').length+'</strong></div></div><div class="grid"><div class="panel"><h2>OS prioritárias</h2>'+table(os.slice().sort((a,b)=>(a.prioridade||9)-(b.prioridade||9)).slice(0,12),[['numero','OS'],['clientes.razao_social','Cliente'],['extrusoras.nome','Extrusora'],['status','Status'],['prazo','Prazo']], 'os')+'</div><div class="panel"><h2>Fábrica agora</h2><div class="machine-grid">'+maq.map(m=>'<div class="machine"><strong>'+esc(m.nome)+'</strong><small>'+esc(m.setor)+'</small><div>'+status(m.status)+'</div></div>').join('')+'</div><h2 style="margin-top:18px">Exceções</h2><div class="timeline"><div class="event"><strong>'+atrasadas+' OS com risco de prazo</strong><small>Priorizar no PCP</small></div><div class="event"><strong>'+nc.filter(x=>x.status!=='encerrada').length+' NC abertas</strong><small>Qualidade</small></div></div></div></div>'},
clientes:async()=>{const data=await q('clientes','id,cnpj,razao_social,nome_fantasia,email,telefone,active',200);return moduleTable('Clientes',data,[['razao_social','Razão social'],['cnpj','CNPJ'],['nome_fantasia','Fantasia'],['email','E-mail'],['active','Ativo']], 'clientes')},
engenharia:async()=>{const data=await q('desenhos','id,numero,perfil_codigo,classe,diametro,comprimento,material,revisao_atual,status,projetos(nome)',200);return moduleTable('Desenhos e projetos',data,[['numero','Desenho'],['perfil_codigo','Perfil'],['projetos.nome','Projeto'],['diametro','Ø'],['comprimento','Comprimento'],['material','Material'],['revisao_atual','Rev.'],['status','Status']], 'desenhos')},
os:async()=>{const data=await q('ordens_servico','id,numero,status,prioridade,prazo,valor,custo_estimado,custo_real,clientes(razao_social),extrusoras(nome)',300);return moduleTable('Ordens de Serviço',data,[['numero','OS'],['clientes.razao_social','Cliente'],['extrusoras.nome','Extrusora'],['status','Status'],['prioridade','Prioridade'],['prazo','Prazo'],['valor','Valor']], 'os')},
pcp:async()=>{const [fila,cap,prog]=await Promise.all([q('filas_producao','id,prioridade,posicao,risco,operacoes_producao(id,status,maquinas(nome))',300),q('capacidade_recursos','id,data,turno,capacidade_min,indisponivel_min,maquinas(nome)',300),q('programacoes','id,inicio_previsto,fim_previsto,prioridade,status,maquinas(nome)',300)]);return '<div class="cards"><div class="card"><small>Fila</small><strong>'+fila.length+'</strong></div><div class="card"><small>Programações</small><strong>'+prog.length+'</strong></div><div class="card"><small>Recursos</small><strong>'+cap.length+'</strong></div><div class="card"><small>Riscos</small><strong>'+fila.filter(x=>x.risco==='risco').length+'</strong></div><div class="card"><small>Capacidade referência</small><strong>17/dia</strong></div></div><div class="grid"><div class="panel"><h2>Fila de produção</h2>'+table(fila,[['posicao','#'],['prioridade','Prioridade'],['risco','Risco'],['operacoes_producao.maquinas.nome','Máquina'],['operacoes_producao.status','Status']])+'</div><div class="panel"><h2>Capacidade</h2>'+table(cap,[['data','Data'],['turno','Turno'],['maquinas.nome','Máquina'],['capacidade_min','Cap. min'],['indisponivel_min','Indisp.']])+'</div></div>'},
producao:async()=>{const [ops,maq]=await Promise.all([q('operacoes_producao','id,status,sequencia,inicio,fim,maquinas(nome),ordens_producao(os_id,componentes_os(codigo))',300),q('maquinas','id,nome,setor,status',100)]);const rows=ops.length?'<div class="table-wrap"><table class="table"><thead><tr><th>Seq.</th><th>Componente</th><th>Máquina</th><th>Status</th><th>Início</th><th>Fim</th><th>Ação</th></tr></thead><tbody>'+ops.map(r=>'<tr><td>'+esc(r.sequencia||'—')+'</td><td>'+esc(r.ordens_producao?.componentes_os?.codigo||'—')+'</td><td>'+esc(r.maquinas?.nome||'—')+'</td><td>'+status(r.status)+'</td><td>'+esc(fmt(r.inicio))+'</td><td>'+esc(fmt(r.fim))+'</td><td class="actions">'+(r.status==='aguardando'||r.status==='pausada'?'<button onclick="window.feljOp(\\''+r.id+'\\',\\'start\\')">Iniciar</button>':'')+(r.status==='em_execucao'?'<button onclick="window.feljOp(\\''+r.id+'\\',\\'pause\\')">Pausar</button><button onclick="window.feljOp(\\''+r.id+'\\',\\'finish\\')">Finalizar</button>':'')+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty">Nenhuma operação cadastrada.</div>';return '<div class="panel"><div class="module-head"><h2>Centro de apontamentos</h2><span>Iniciar · Pausar · Finalizar</span></div>'+rows+'</div><div class="panel" style="margin-top:16px"><h2>Máquinas</h2><div class="machine-grid">'+maq.map(m=>'<div class="machine"><strong>'+esc(m.nome)+'</strong><small>'+esc(m.setor)+'</small>'+status(m.status)+'</div>').join('')+'</div></div>'},estoque:async()=>{const [mat,lotes,itens,rem]=await Promise.all([q('materiais','id,codigo,descricao,material,diametro,comprimento',300),q('lotes_materiais','id,lote,heat,fornecedor,bloqueado,materiais(descricao,material)',300),q('itens_estoque','id,saldo,reservado,estoques(nome),lotes_materiais(lote,material_id)',300),q('remanescentes','id,diametro,comprimento,quantidade,localizacao,status',200)]);return '<div class="cards"><div class="card"><small>Materiais</small><strong>'+mat.length+'</strong></div><div class="card"><small>Lotes</small><strong>'+lotes.length+'</strong></div><div class="card"><small>Bloqueados</small><strong>'+lotes.filter(x=>x.bloqueado).length+'</strong></div><div class="card"><small>Saldo reservado</small><strong>'+itens.reduce((s,x)=>s+(x.reservado||0),0).toLocaleString('pt-BR')+'</strong></div><div class="card"><small>Remanescentes</small><strong>'+rem.length+'</strong></div></div><div class="grid"><div class="panel"><h2>Lotes rastreáveis</h2>'+table(lotes,[['lote','Lote'],['heat','Heat'],['materiais.descricao','Material'],['fornecedor','Fornecedor'],['bloqueado','Bloqueado']])+'</div><div class="panel"><h2>Saldo de estoque</h2>'+table(itens,[['estoques.nome','Estoque'],['lotes_materiais.lote','Lote'],['saldo','Saldo'],['reservado','Reservado']])+'</div></div>'},
qualidade:async()=>{const [ins,nc,instr]=await Promise.all([q('inspecoes','id,status,resultado,nominal,tolerancia_min,tolerancia_max,data_hora,componentes_os(codigo),instrumentos_medicao(codigo)',300),q('nao_conformidades','id,descricao,severidade,status,created_at,componentes_os(codigo)',300),q('instrumentos_medicao','id,codigo,nome,validade,status',200)]);return '<div class="cards"><div class="card"><small>Inspeções</small><strong>'+ins.length+'</strong></div><div class="card"><small>Reprovadas</small><strong>'+ins.filter(x=>x.status==='reprovado').length+'</strong></div><div class="card"><small>NC abertas</small><strong>'+nc.filter(x=>x.status!=='encerrada').length+'</strong></div><div class="card"><small>Instrumentos</small><strong>'+instr.length+'</strong></div><div class="card"><small>Vencidos</small><strong>'+instr.filter(x=>x.validade&&new Date(x.validade)<new Date()).length+'</strong></div></div><div class="grid"><div class="panel"><h2>Inspeções</h2>'+table(ins,[['componentes_os.codigo','Componente'],['resultado','Resultado'],['nominal','Nominal'],['status','Status'],['data_hora','Data']])+'</div><div class="panel"><h2>Não conformidades</h2>'+table(nc,[['componentes_os.codigo','Componente'],['descricao','Descrição'],['severidade','Severidade'],['status','Status']])+'</div></div>'},
custos:async()=>{const data=await q('custos_os','id,os_id,aco,mao_obra,maquina,setup,terceiros,tempera,erosao,retrabalho,sucata,outros,ordens_servico(numero,valor,custo_estimado)',300);return moduleTable('Custos por OS',data,[['ordens_servico.numero','OS'],['ordens_servico.valor','Venda'],['ordens_servico.custo_estimado','Estimado'],['aco','Aço'],['mao_obra','Mão de obra'],['maquina','Máquina'],['terceiros','Terceiros'],['retrabalho','Retrabalho']], 'custos')},
expedicao:async()=>{const [fat,exp,ent]=await Promise.all([q('faturamentos','id,os_id,valor,nf,data,status,ordens_servico(numero,clientes(razao_social))',300),q('expedicoes','id,os_id,nf,transportadora,peso,rastreio,status,data_expedicao,ordens_servico(numero)',300),q('entregas','id,expedicao_id,entregue_em,recebido_por,status',300)]);return '<div class="grid"><div class="panel"><h2>Faturamento</h2>'+table(fat,[['ordens_servico.numero','OS'],['ordens_servico.clientes.razao_social','Cliente'],['valor','Valor'],['nf','NF'],['status','Status']])+'</div><div class="panel"><h2>Expedições</h2>'+table(exp,[['ordens_servico.numero','OS'],['transportadora','Transportadora'],['nf','NF'],['rastreio','Rastreio'],['status','Status']])+'</div></div>'},
correcoes:async()=>{const data=await q('correction_records','id,client,os,reference,request_type,status,received_at,due_at,assignee,requires_review',300);return moduleTable('Correções / Recuperações / Alterações',data,[['client','Cliente'],['os','OS'],['request_type','Tipo'],['status','Status'],['received_at','Entrada'],['due_at','Prazo'],['assignee','Responsável']], 'correcoes')}
};
function table(rows,cols,kind){if(!rows.length)return '<div class="empty">Nenhum registro.</div>';const get=(o,path)=>path.split('.').reduce((a,k)=>a?.[k],o);return '<div class="table-wrap"><table class="table"><thead><tr>'+cols.map(c=>'<th>'+c[1]+'</th>').join('')+(kind?'<th>Ação</th>':'')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+((c[0]==='status')?status(get(r,c[0])):c[0].includes('prazo')||c[0].includes('data')||c[0].includes('at')?esc(fmt(get(r,c[0]))):esc(get(r,c[0])??'—'))+'</td>').join('')+(kind?'<td class="actions"><button onclick="window.feljOpen(\''+r.id+'\',\''+kind+'\')">Abrir</button></td>':'')+'</tr>').join('')+'</tbody></table></div>'}
function moduleTable(title,data,cols,kind){return '<div class="panel"><div class="module-head"><h2>'+title+'</h2><button class="primary" onclick="window.feljNew(\''+kind+'\')">+ Novo</button></div><div class="filters"><input placeholder="Filtro rápido" oninput="window.feljFilter(this)"></div><div data-table>'+table(data,cols,kind)+'</div></div>'}
window.feljOp=async(id,action)=>{try{let r;if(action==='start')r=await supabase.rpc('iniciar_operacao',{p_operacao_id:id});if(action==='pause')r=await supabase.rpc('pausar_operacao',{p_operacao_id:id,p_motivo_id:null,p_observacao:'Pausa pelo painel PCP'});if(action==='finish')r=await supabase.rpc('finalizar_operacao',{p_operacao_id:id,p_quantidade_boa:1,p_quantidade_rejeitada:0,p_observacao:'Finalização pelo painel'});if(r.error)throw r.error;await renderPage()}catch(e){alert('Não foi possível atualizar a operação: '+e.message)}};window.feljFilter=input=>{const term=input.value.toLowerCase();input.closest('.panel').querySelectorAll('tbody tr').forEach(tr=>tr.style.display=tr.innerText.toLowerCase().includes(term)?'':'none')};
window.feljNew=kind=>openRecord(kind);
window.feljOpen=(id,kind)=>openRecord(kind,id);
async function openRecord(kind,id){const defs={clientes:{table:'clientes',title:'Cliente',fields:[['razao_social','Razão social','text',true],['cnpj','CNPJ','text'],['nome_fantasia','Nome fantasia','text'],['email','E-mail','email'],['telefone','Telefone','text'],['observacoes','Observações','textarea']]},desenhos:{table:'desenhos',title:'Desenho',fields:[['numero','Número','text',true],['perfil_codigo','Código do perfil','text'],['classe','Classe','text'],['diametro','Diâmetro','number'],['comprimento','Comprimento','number'],['material','Material','text'],['revisao_atual','Revisão','text']]},os:{table:'ordens_servico',title:'Ordem de Serviço',fields:[['numero','Número da OS','text',true],['prioridade','Prioridade','number'],['prazo','Prazo','date'],['status','Status','text'],['valor','Valor','number']]},custos:{table:'custos_os',title:'Custo da OS',fields:[['os_id','ID da OS','text',true],['aco','Aço','number'],['mao_obra','Mão de obra','number'],['maquina','Máquina','number'],['terceiros','Terceiros','number'],['retrabalho','Retrabalho','number']]};const d=defs[kind];if(!d)return;let row=null;if(id){const r=await supabase.from(d.table).select('*').eq('id',id).single();row=r.data}$('#recordTitle').textContent=(id?'Editar ':'Novo ')+d.title;$('#recordFields').innerHTML='<div class="field-grid">'+d.fields.map(f=>'<div class="field '+(f[2]==='textarea'?'full':'')+'"><label>'+f[1]+'</label>'+(f[2]==='textarea'?'<textarea name="'+f[0]+'">'+esc(row?.[f[0]]||'')+'</textarea>':'<input name="'+f[0]+'" type="'+f[2]+'" value="'+esc(row?.[f[0]]??'')+'" '+(f[3]?'required':'')+'>')+'</div>').join('')+'</div>';$('#recordForm').dataset.table=d.table;$('#recordForm').dataset.id=id||'';$('#recordDialog').showModal()}
async function saveRecord(e){e.preventDefault();const form=e.currentTarget,data={};new FormData(form).forEach((v,k)=>data[k]=v);for(const k of Object.keys(data))if(data[k]==='')data[k]=null;let r;if(form.dataset.id)r=await supabase.from(form.dataset.table).update(data).eq('id',form.dataset.id);else r=await supabase.from(form.dataset.table).insert(data);if(r.error){$('#recordError').textContent=r.error.message;return}$('#recordDialog').close();renderPage()}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(!b)return;$$('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');page=b.dataset.page;renderPage()});
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const r=await supabase.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(r.error)$('#authError').textContent=r.error.message;else $('#authDialog').close()});
$('#recordForm').addEventListener('submit',saveRecord);$$('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#recordDialog').close()));$('#logout').onclick=()=>supabase.auth.signOut();
$('#globalSearch').addEventListener('keydown',async e=>{if(e.key!=='Enter')return;const term=e.target.value.trim();if(!term)return;const r=await supabase.from('ordens_servico').select('id,numero,status,clientes(razao_social)').or('numero.ilike.%'+term+'%').limit(20);$('#content').innerHTML='<div class="panel"><h2>Pesquisa global</h2>'+table(r.data||[],[['numero','OS'],['clientes.razao_social','Cliente'],['status','Status']])+'</div>'});
init();
})();